new changes

diff --git a/.github/workflows/PushtoRepo.yml b/.github/workflows/PushtoRepo.yml
--- a/.github/workflows/PushtoRepo.yml
+++ b/.github/workflows/PushtoRepo.yml
@@ -8,21 +8,27 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Install GitHub CLI
+      run: |
+        sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
+        sudo apt-add-repository https://cli.github.com/packages
+        sudo apt-get update
+        sudo apt-get install gh
+
     - name: Checkout source code
       uses: actions/checkout@v2
 
     - name: Create branch in target repository
       env:
-        TARGET_REPO_TOKEN: ${{ secrets.TARGET_REPO_TOKEN }}
         TARGET_REPO_USERNAME: gvilela7
         TARGET_REPO_NAME: dryrun_vilela
       run: |
-        # Set up Git
-        git config --global user.email "actions@github.com"
-        git config --global user.name "GitHub Actions"
+        # Authenticate with GitHub CLI using the token
+        gh auth login --with-token <<< "${{ secrets.TARGET_REPO_TOKEN }}"
 
-        # Push the new branch to the target repository
-        git push https://$TARGET_REPO_USERNAME:$TARGET_REPO_TOKEN@github.com/$TARGET_REPO_USERNAME/$TARGET_REPO_NAME.git HEAD:new_branch_name || echo "Failed to push branch to target repository"
-        
+        # Create a new branch in the target repository
+        gh repo create $TARGET_REPO_USERNAME/$TARGET_REPO_NAME -p
+        git push origin HEAD:new_branch_name || echo "Failed to push branch to target repository"
+
         # Show remotes for debugging
         git remote -v
